language: csharp
mono: none
sudo: required
dotnet: 2.0.0
dist: xenial
before_script: 
    - dotnet restore ".\Travis.Tests.Build\TravisBuild\TravisBuild.sln"
script: 
    - dotnet build ".\Travis.Tests.Build\TravisBuild\TravisBuild.sln" -c Release
    - dotnet test ".\Travis.Tests.Build\TravisBuild\TravisBuild.sln" -c Release -v n